//
//  ViewController.swift
//  MON.MARCH.9.2020.STEPPERS.SLIDERS
//
//  Created by Tech on 2020-03-09.
//  Copyright © 2020 Tech. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var lblStepperOutput: UILabel!
    @IBOutlet weak var outletStepper: UIStepper!

    @IBAction func actionStepper(_ sender: UIStepper) {
        // output generated by stepper (capture values)
        print(sender.value);
        lblStepperOutput.text = String(sender.value);
    }
    
    @IBAction func btnReset(_ sender: UIButton) {
        outletStepper.value = 50;
        lblStepperOutput.text = String(outletStepper.value);
        print("value has been reset to \(outletStepper.value)");
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }


    
}

